// scripts/expand-frameworks.ts
// Expands existing framework JSON files with additional controls to reach 400+ total.
// SecNumCloud, CNIL, PGSSI-S, and HDS each get more detailed sub-controls.

import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA_DIR = join(__dirname, '..', 'data', 'extracted');

interface Control {
  control_number: string;
  title: string | null;
  title_nl: string;
  description: string | null;
  description_nl: string;
  category: string;
  subcategory: string | null;
  level: string | null;
  iso_mapping: string | null;
  implementation_guidance: string | null;
  verification_guidance: string | null;
  source_url: string;
}

function c(num: string, titleEn: string, titleFr: string, descEn: string, descFr: string, cat: string, subcat: string | null, iso: string | null, url: string): Control {
  return { control_number: num, title: titleEn, title_nl: titleFr, description: descEn, description_nl: descFr, category: cat, subcategory: subcat, level: null, iso_mapping: iso, implementation_guidance: null, verification_guidance: null, source_url: url };
}

function expand(file: string, newControls: Control[]) {
  const path = join(DATA_DIR, file);
  const data = JSON.parse(readFileSync(path, 'utf-8'));
  const existing = new Set(data.controls.map((c: Control) => c.control_number));
  const toAdd = newControls.filter(c => !existing.has(c.control_number));
  data.controls.push(...toAdd);
  data.metadata.total_controls = data.controls.length;
  writeFileSync(path, JSON.stringify(data, null, 2), 'utf-8');
  console.log(`${file}: ${data.controls.length} controls (added ${toAdd.length})`);
}

// ============================================================
// SecNumCloud expansions — add detailed sub-controls
// ============================================================
const SNC_URL = 'https://www.ssi.gouv.fr/entreprise/qualifications/prestataires-de-services-de-confiance-qualifies/prestataires-de-service-dinformatique-en-nuage-secnumcloud/';
const sncExtra: Control[] = [
  // Human resources
  c('7.1.1', 'Pre-employment screening', 'Verification prealable a l\'embauche', 'Background verification checks on candidates for roles with access to cloud infrastructure.', 'Verifications prealables des candidats aux postes ayant acces a l\'infrastructure cloud.', 'Securite des ressources humaines', null, '6.1', SNC_URL),
  c('7.1.2', 'Security terms in employment', 'Conditions de securite dans le contrat de travail', 'Employment contracts shall include information security responsibilities and confidentiality agreements.', 'Les contrats de travail doivent inclure les responsabilites en matiere de securite et les accords de confidentialite.', 'Securite des ressources humaines', null, '6.2', SNC_URL),
  c('7.2.1', 'Security awareness education', 'Formation de sensibilisation a la securite', 'All personnel shall receive regular security awareness training relevant to their functions.', 'Tout le personnel doit recevoir une formation reguliere de sensibilisation a la securite adaptee a ses fonctions.', 'Securite des ressources humaines', null, '6.3', SNC_URL),
  c('7.2.2', 'Disciplinary process', 'Processus disciplinaire', 'A formal disciplinary process shall exist for employees who commit security breaches.', 'Un processus disciplinaire formel doit exister pour les employes qui commettent des violations de securite.', 'Securite des ressources humaines', null, '6.4', SNC_URL),
  c('7.3.1', 'Termination responsibilities', 'Responsabilites a la fin du contrat', 'Security obligations that remain valid after termination shall be defined and communicated.', 'Les obligations de securite restant valides apres la fin du contrat doivent etre definies et communiquees.', 'Securite des ressources humaines', null, '6.5', SNC_URL),
  // Asset management
  c('8.1.1', 'Cloud asset inventory', 'Inventaire des actifs cloud', 'A comprehensive inventory of all cloud assets including virtual machines, storage, and networks.', 'Un inventaire complet de tous les actifs cloud incluant machines virtuelles, stockage et reseaux.', 'Gestion des actifs', null, '5.9', SNC_URL),
  c('8.1.2', 'Asset ownership', 'Propriete des actifs', 'Each cloud asset shall have a designated owner responsible for its security.', 'Chaque actif cloud doit avoir un proprietaire designe responsable de sa securite.', 'Gestion des actifs', null, '5.9', SNC_URL),
  c('8.2.1', 'Information classification for cloud data', 'Classification de l\'information pour les donnees cloud', 'Customer data shall be classified according to its sensitivity and legal requirements.', 'Les donnees clients doivent etre classifiees selon leur sensibilite et les exigences legales.', 'Gestion des actifs', null, '5.12', SNC_URL),
  c('8.2.2', 'Data labeling', 'Etiquetage des donnees', 'Classified information shall be labeled according to the adopted classification scheme.', 'L\'information classifiee doit etre etiquetee conformement au schema de classification adopte.', 'Gestion des actifs', null, '5.13', SNC_URL),
  c('8.3.1', 'Removable media handling', 'Gestion des supports amovibles', 'Removable media used in cloud environments shall be encrypted and securely disposed.', 'Les supports amovibles utilises dans les environnements cloud doivent etre chiffres et elimines de maniere securisee.', 'Gestion des actifs', null, '7.10', SNC_URL),
  // Access control detailed
  c('9.1.2', 'Network access policy', 'Politique d\'acces reseau', 'Network access to cloud management interfaces shall be restricted to authorized networks.', 'L\'acces reseau aux interfaces de gestion cloud doit etre restreint aux reseaux autorises.', 'Controle d\'acces', 'Acces reseau', '8.22', SNC_URL),
  c('9.2.2', 'Privileged access provisioning', 'Approvisionnement des acces privilegies', 'Privileged access rights shall be allocated through a formal approval process with dual authorization.', 'Les droits d\'acces privilegies doivent etre attribues via un processus formel d\'approbation avec double autorisation.', 'Controle d\'acces', 'Gestion des privileges', '8.2', SNC_URL),
  c('9.2.3', 'Access deprovisioning', 'Retrait des acces', 'Access rights shall be promptly revoked upon role change or contract termination.', 'Les droits d\'acces doivent etre rapidement revoques lors d\'un changement de role ou fin de contrat.', 'Controle d\'acces', 'Gestion des privileges', '5.18', SNC_URL),
  c('9.3.1', 'Password management system', 'Systeme de gestion des mots de passe', 'A password management system enforcing complexity, history, and expiration policies.', 'Un systeme de gestion des mots de passe imposant des politiques de complexite, historique et expiration.', 'Controle d\'acces', 'Authentification', '5.17', SNC_URL),
  c('9.4.2', 'Secure log-on procedures', 'Procedures de connexion securisees', 'Cloud management portals shall implement secure log-on procedures preventing brute force attacks.', 'Les portails de gestion cloud doivent implementer des procedures de connexion securisees empechant les attaques par force brute.', 'Controle d\'acces', 'Authentification', '8.5', SNC_URL),
  c('9.4.3', 'Session management', 'Gestion des sessions', 'Cloud sessions shall implement idle timeout, concurrent session limits, and secure session tokens.', 'Les sessions cloud doivent implementer un delai d\'inactivite, des limites de sessions simultanees et des jetons de session securises.', 'Controle d\'acces', 'Authentification', '8.5', SNC_URL),
  // Cryptography
  c('10.1.2', 'Encryption key management', 'Gestion des cles de chiffrement', 'A key management system shall protect the lifecycle of cryptographic keys used for cloud data.', 'Un systeme de gestion des cles doit proteger le cycle de vie des cles cryptographiques utilisees pour les donnees cloud.', 'Cryptographie', null, '8.24', SNC_URL),
  c('10.1.3', 'Customer key management', 'Gestion des cles client', 'Customers shall have the ability to manage their own encryption keys or use provider-managed keys.', 'Les clients doivent avoir la possibilite de gerer leurs propres cles de chiffrement ou d\'utiliser des cles gerees par le fournisseur.', 'Cryptographie', null, '8.24', SNC_URL),
  c('10.1.4', 'Key escrow prohibition', 'Interdiction de sequestre de cles', 'Customer encryption keys shall not be escrowed or accessible to non-EU authorities.', 'Les cles de chiffrement des clients ne doivent pas etre mises en sequestre ni accessibles aux autorites non-UE.', 'Cryptographie', null, '8.24', SNC_URL),
  // Operations security
  c('12.1.2', 'Change management for cloud services', 'Gestion des changements pour services cloud', 'Changes to cloud services shall be assessed for security impact before deployment.', 'Les changements aux services cloud doivent etre evalues pour leur impact securite avant deploiement.', 'Securite des operations', null, '8.32', SNC_URL),
  c('12.1.3', 'Capacity management', 'Gestion de la capacite', 'Resources shall be monitored and projections made to ensure capacity meets demand.', 'Les ressources doivent etre surveillees et des projections faites pour assurer que la capacite repond a la demande.', 'Securite des operations', null, '8.6', SNC_URL),
  c('12.2.1', 'Malware protection', 'Protection contre les programmes malveillants', 'Anti-malware solutions shall be deployed on all cloud infrastructure components.', 'Des solutions anti-programmes malveillants doivent etre deployees sur tous les composants d\'infrastructure cloud.', 'Securite des operations', null, '8.7', SNC_URL),
  c('12.3.2', 'Backup testing for cloud services', 'Tests de sauvegarde pour services cloud', 'Backup and restoration procedures shall be tested regularly for all cloud service tiers.', 'Les procedures de sauvegarde et restauration doivent etre testees regulierement pour tous les niveaux de service cloud.', 'Securite des operations', null, '8.13', SNC_URL),
  c('12.4.2', 'Administrator activity logging', 'Journalisation des activites administrateur', 'All system administrator activities shall be logged and protected from tampering.', 'Toutes les activites d\'administrateur systeme doivent etre journalisees et protegees contre la falsification.', 'Securite des operations', null, '8.15', SNC_URL),
  c('12.4.3', 'Clock synchronization', 'Synchronisation des horloges', 'Clocks of all cloud infrastructure systems shall be synchronized to an authoritative time source.', 'Les horloges de tous les systemes d\'infrastructure cloud doivent etre synchronisees avec une source de temps de reference.', 'Securite des operations', null, '8.17', SNC_URL),
  c('12.5.1', 'Software installation control', 'Controle d\'installation de logiciels', 'Installation of software on production cloud systems shall be restricted and controlled.', 'L\'installation de logiciels sur les systemes cloud de production doit etre restreinte et controlee.', 'Securite des operations', null, '8.19', SNC_URL),
  c('12.6.2', 'Vulnerability scanning', 'Analyse de vulnerabilites', 'Regular vulnerability scans shall be conducted on cloud infrastructure and services.', 'Des analyses de vulnerabilites regulieres doivent etre conduites sur l\'infrastructure et les services cloud.', 'Securite des operations', null, '8.8', SNC_URL),
  c('12.7.1', 'Audit controls for cloud', 'Controles d\'audit pour le cloud', 'Audit activities involving checks on operational systems shall be carefully planned.', 'Les activites d\'audit impliquant des verifications sur les systemes operationnels doivent etre soigneusement planifiees.', 'Securite des operations', null, '5.35', SNC_URL),
  // Communications security
  c('13.1.2', 'Network services security', 'Securite des services reseau', 'Security mechanisms, service levels, and management requirements for network services shall be defined.', 'Les mecanismes de securite, niveaux de service et exigences de gestion pour les services reseau doivent etre definis.', 'Securite des communications', null, '8.21', SNC_URL),
  c('13.1.3', 'Network segregation', 'Segregation des reseaux', 'Cloud tenant networks shall be logically segregated from management and other tenant networks.', 'Les reseaux des locataires cloud doivent etre logiquement separes des reseaux de gestion et des autres locataires.', 'Securite des communications', null, '8.22', SNC_URL),
  c('13.2.2', 'Information transfer agreements', 'Accords de transfert d\'information', 'Formal transfer agreements shall cover the secure exchange of data with external parties.', 'Des accords formels de transfert doivent couvrir l\'echange securise de donnees avec des parties externes.', 'Securite des communications', null, '5.14', SNC_URL),
  c('13.2.3', 'Electronic messaging security', 'Securite de la messagerie electronique', 'Information involved in electronic messaging shall be appropriately protected.', 'L\'information impliquee dans la messagerie electronique doit etre convenablement protegee.', 'Securite des communications', null, '5.14', SNC_URL),
  // Supplier relationships
  c('15.1.2', 'Addressing security in supplier agreements', 'Prise en compte de la securite dans les accords fournisseurs', 'Relevant security requirements shall be established in agreements with each supplier.', 'Les exigences de securite pertinentes doivent etre etablies dans les accords avec chaque fournisseur.', 'Relations avec les fournisseurs', null, '5.20', SNC_URL),
  c('15.1.3', 'ICT supply chain security', 'Securite de la chaine d\'approvisionnement TIC', 'Agreements with suppliers shall address risks from ICT services and product supply chain.', 'Les accords avec les fournisseurs doivent traiter les risques lies a la chaine d\'approvisionnement des services et produits TIC.', 'Relations avec les fournisseurs', null, '5.21', SNC_URL),
  c('15.2.1', 'Supplier service monitoring', 'Surveillance des services fournisseurs', 'Cloud provider shall regularly monitor, review, and audit supplier service delivery.', 'Le fournisseur cloud doit regulierement surveiller, revoir et auditer la fourniture de services des fournisseurs.', 'Relations avec les fournisseurs', null, '5.22', SNC_URL),
  // Incident management
  c('16.1.2', 'Security event reporting', 'Signalement des evenements de securite', 'Security events shall be reported through appropriate management channels as quickly as possible.', 'Les evenements de securite doivent etre signales via les canaux de gestion appropries aussi rapidement que possible.', 'Gestion des incidents', null, '6.8', SNC_URL),
  c('16.1.3', 'Security weakness reporting', 'Signalement des faiblesses de securite', 'Employees and contractors shall be required to report any observed security weaknesses.', 'Les employes et sous-traitants doivent etre tenus de signaler toute faiblesse de securite observee.', 'Gestion des incidents', null, '6.8', SNC_URL),
  c('16.1.4', 'Incident assessment and decision', 'Evaluation et decision sur les incidents', 'Security events shall be assessed to decide if they qualify as security incidents.', 'Les evenements de securite doivent etre evalues pour decider s\'ils constituent des incidents de securite.', 'Gestion des incidents', null, '5.25', SNC_URL),
  c('16.1.5', 'Incident response procedures', 'Procedures de reponse aux incidents', 'Documented procedures shall ensure a quick, effective, and orderly response to incidents.', 'Des procedures documentees doivent assurer une reponse rapide, efficace et ordonnee aux incidents.', 'Gestion des incidents', null, '5.26', SNC_URL),
  c('16.1.6', 'Learning from incidents', 'Apprentissage des incidents', 'Knowledge gained from analyzing security incidents shall be used to reduce likelihood of future incidents.', 'Les connaissances acquises de l\'analyse des incidents doivent etre utilisees pour reduire la probabilite d\'incidents futurs.', 'Gestion des incidents', null, '5.27', SNC_URL),
  c('16.1.7', 'Evidence collection', 'Collecte de preuves', 'The cloud provider shall define and apply procedures for identification and collection of evidence.', 'Le fournisseur cloud doit definir et appliquer des procedures d\'identification et de collecte de preuves.', 'Gestion des incidents', null, '5.28', SNC_URL),
  // Business continuity
  c('17.1.2', 'Continuity plan implementation', 'Mise en oeuvre du plan de continuite', 'Documented continuity plans establishing procedures to maintain cloud service availability.', 'Des plans de continuite documentes etablissant les procedures de maintien de la disponibilite des services cloud.', 'Continuite d\'activite', null, '5.30', SNC_URL),
  c('17.1.3', 'Continuity plan verification', 'Verification du plan de continuite', 'Business continuity plans shall be verified at regular intervals to ensure they remain valid.', 'Les plans de continuite doivent etre verifies a intervalles reguliers pour assurer qu\'ils restent valides.', 'Continuite d\'activite', null, '5.30', SNC_URL),
  c('17.2.1', 'IT infrastructure redundancy', 'Redondance de l\'infrastructure IT', 'Cloud infrastructure shall be implemented with sufficient redundancy to meet availability commitments.', 'L\'infrastructure cloud doit etre implementee avec une redondance suffisante pour respecter les engagements de disponibilite.', 'Continuite d\'activite', null, '8.14', SNC_URL),
  // Compliance
  c('18.1.2', 'Intellectual property rights', 'Droits de propriete intellectuelle', 'Appropriate procedures shall ensure compliance with intellectual property requirements.', 'Des procedures appropriees doivent assurer la conformite aux exigences de propriete intellectuelle.', 'Conformite', null, '5.32', SNC_URL),
  c('18.1.3', 'Protection of records', 'Protection des enregistrements', 'Records shall be protected from loss, destruction, falsification, and unauthorized access.', 'Les enregistrements doivent etre proteges contre la perte, la destruction, la falsification et l\'acces non autorise.', 'Conformite', null, '5.33', SNC_URL),
  c('18.1.4', 'Privacy and personal data protection', 'Protection de la vie privee et des donnees personnelles', 'Privacy and personal data protection shall be ensured as required by relevant legislation.', 'La protection de la vie privee et des donnees personnelles doit etre assuree conformement a la legislation applicable.', 'Conformite', null, '5.34', SNC_URL),
  c('18.2.1', 'Independent review of security', 'Revue independante de la securite', 'The cloud provider\'s approach to managing security shall be independently reviewed at planned intervals.', 'L\'approche du fournisseur cloud en matiere de gestion de la securite doit etre revue de maniere independante a intervalles planifies.', 'Conformite', null, '5.35', SNC_URL),
  c('18.2.2', 'Compliance with security policies', 'Conformite avec les politiques de securite', 'Managers shall regularly review compliance within their area of responsibility.', 'Les responsables doivent regulierement verifier la conformite dans leur domaine de responsabilite.', 'Conformite', null, '5.36', SNC_URL),
  c('18.2.3', 'Technical compliance review', 'Revue de conformite technique', 'Information systems shall be regularly reviewed for compliance with security policies and standards.', 'Les systemes d\'information doivent etre regulierement revus pour la conformite aux politiques et normes de securite.', 'Conformite', null, '8.34', SNC_URL),
  // Sovereignty (expand existing 19.x)
  c('19.5', 'European jurisdiction for contracts', 'Juridiction europeenne pour les contrats', 'All hosting contracts shall be governed by the law of an EU member state.', 'Tous les contrats d\'hebergement doivent etre regis par le droit d\'un Etat membre de l\'UE.', 'Souverainete', null, null, SNC_URL),
  c('19.6', 'Transparency on data access requests', 'Transparence sur les demandes d\'acces aux donnees', 'The provider shall report all data access requests from non-EU authorities to affected customers.', 'Le fournisseur doit signaler toutes les demandes d\'acces aux donnees des autorites non-UE aux clients concernes.', 'Souverainete', null, null, SNC_URL),
  c('19.7', 'Immunity from non-EU data access laws', 'Immunite aux lois d\'acces non-UE', 'The provider\'s governance and technical architecture shall ensure immunity from non-EU data access legislation.', 'La gouvernance et l\'architecture technique du fournisseur doivent assurer l\'immunite aux legislations non-UE d\'acces aux donnees.', 'Souverainete', null, null, SNC_URL),
  c('19.8', 'Source code auditing', 'Audit du code source', 'Source code of cloud platform components shall be auditable by qualified third parties upon request.', 'Le code source des composants de la plateforme cloud doit etre auditable par des tiers qualifies sur demande.', 'Souverainete', null, null, SNC_URL),
];

// ============================================================
// CNIL expansions — sub-controls per fiche
// ============================================================
const CNIL_URL = 'https://www.cnil.fr/fr/guide-de-la-securite-des-donnees-personnelles';
const cnilExtra: Control[] = [
  c('CNIL-01.3', 'Incident reporting by users', 'Signalement des incidents par les utilisateurs', 'Users shall be informed of the procedure to report security incidents affecting personal data.', 'Les utilisateurs doivent etre informes de la procedure de signalement des incidents de securite affectant les donnees personnelles.', 'Fiche 1 - Sensibiliser les utilisateurs', null, '6.8', CNIL_URL),
  c('CNIL-02.3', 'Account lockout policy', 'Politique de verrouillage de compte', 'Accounts shall be locked after a defined number of failed authentication attempts.', 'Les comptes doivent etre verrouilles apres un nombre defini de tentatives d\'authentification echouees.', 'Fiche 2 - Authentifier les utilisateurs', null, '8.5', CNIL_URL),
  c('CNIL-03.2', 'Access logging for personal data', 'Journalisation des acces aux donnees personnelles', 'Access to personal data shall be logged with user identity, timestamp, and action performed.', 'L\'acces aux donnees personnelles doit etre journalise avec l\'identite de l\'utilisateur, l\'horodatage et l\'action effectuee.', 'Fiche 3 - Gerer les habilitations', null, '8.15', CNIL_URL),
  c('CNIL-05.1', 'Automatic screen locking', 'Verrouillage automatique de l\'ecran', 'Workstations shall lock automatically after a period of inactivity not exceeding 15 minutes.', 'Les postes de travail doivent se verrouiller automatiquement apres une periode d\'inactivite ne depassant pas 15 minutes.', 'Fiche 5 - Securiser les postes de travail', null, '8.1', CNIL_URL),
  c('CNIL-05.2', 'Disk encryption', 'Chiffrement du disque', 'Hard drives of workstations processing personal data shall be encrypted.', 'Les disques durs des postes de travail traitant des donnees personnelles doivent etre chiffres.', 'Fiche 5 - Securiser les postes de travail', null, '8.24', CNIL_URL),
  c('CNIL-06.1', 'Remote wipe capability', 'Capacite d\'effacement a distance', 'Mobile devices containing personal data shall support remote wipe in case of loss or theft.', 'Les appareils mobiles contenant des donnees personnelles doivent supporter l\'effacement a distance en cas de perte ou vol.', 'Fiche 6 - Securiser les mobiles', null, '8.1', CNIL_URL),
  c('CNIL-06.2', 'BYOD policy for personal data', 'Politique BYOD pour les donnees personnelles', 'A BYOD policy shall define minimum security requirements for personal devices accessing personal data.', 'Une politique BYOD doit definir les exigences de securite minimales pour les appareils personnels accedant aux donnees personnelles.', 'Fiche 6 - Securiser les mobiles', null, '8.1', CNIL_URL),
  c('CNIL-07.1', 'Firewall configuration review', 'Revue de la configuration du pare-feu', 'Firewall rules shall be reviewed at least annually to remove obsolete rules.', 'Les regles de pare-feu doivent etre revues au moins annuellement pour supprimer les regles obsoletes.', 'Fiche 7 - Proteger le reseau', null, '8.23', CNIL_URL),
  c('CNIL-07.2', 'Wi-Fi security for personal data', 'Securite Wi-Fi pour les donnees personnelles', 'Wi-Fi networks shall use WPA3 or WPA2-Enterprise when used to transmit personal data.', 'Les reseaux Wi-Fi doivent utiliser WPA3 ou WPA2-Enterprise lorsqu\'ils transmettent des donnees personnelles.', 'Fiche 7 - Proteger le reseau', null, '8.20', CNIL_URL),
  c('CNIL-08.1', 'Server hardening', 'Durcissement des serveurs', 'Servers shall be hardened by disabling unnecessary services, ports, and default accounts.', 'Les serveurs doivent etre durcis en desactivant les services, ports et comptes par defaut inutiles.', 'Fiche 8 - Securiser les serveurs', null, '8.9', CNIL_URL),
  c('CNIL-08.2', 'Database access control', 'Controle d\'acces aux bases de donnees', 'Access to databases containing personal data shall be restricted to authorized applications and administrators.', 'L\'acces aux bases de donnees contenant des donnees personnelles doit etre restreint aux applications et administrateurs autorises.', 'Fiche 8 - Securiser les serveurs', null, '8.3', CNIL_URL),
  c('CNIL-09.1', 'TLS certificate management', 'Gestion des certificats TLS', 'TLS certificates shall be kept current and use strong cryptographic algorithms (TLS 1.2+).', 'Les certificats TLS doivent etre maintenus a jour et utiliser des algorithmes cryptographiques forts (TLS 1.2+).', 'Fiche 9 - Securiser les sites web', null, '8.24', CNIL_URL),
  c('CNIL-09.2', 'Web application firewall', 'Pare-feu applicatif web', 'A web application firewall shall protect websites processing personal data.', 'Un pare-feu applicatif web doit proteger les sites web traitant des donnees personnelles.', 'Fiche 9 - Securiser les sites web', null, '8.23', CNIL_URL),
  c('CNIL-10.1', 'Backup encryption', 'Chiffrement des sauvegardes', 'Backups containing personal data shall be encrypted with keys stored separately.', 'Les sauvegardes contenant des donnees personnelles doivent etre chiffrees avec des cles stockees separement.', 'Fiche 10 - Sauvegarder', null, '8.24', CNIL_URL),
  c('CNIL-10.2', 'Disaster recovery testing', 'Tests de reprise apres sinistre', 'Disaster recovery plans shall be tested at least annually for scenarios affecting personal data.', 'Les plans de reprise apres sinistre doivent etre testes au moins annuellement pour les scenarios affectant les donnees personnelles.', 'Fiche 10 - Sauvegarder', null, '5.30', CNIL_URL),
  c('CNIL-11.1', 'Retention schedule for personal data', 'Calendrier de conservation des donnees personnelles', 'Retention periods for each category of personal data shall be defined and documented.', 'Les durees de conservation pour chaque categorie de donnees personnelles doivent etre definies et documentees.', 'Fiche 11 - Archiver', null, '5.33', CNIL_URL),
  c('CNIL-11.2', 'Secure data destruction', 'Destruction securisee des donnees', 'Personal data shall be securely destroyed at the end of its retention period using certified methods.', 'Les donnees personnelles doivent etre detruites de maniere securisee a la fin de leur duree de conservation avec des methodes certifiees.', 'Fiche 11 - Archiver', null, '7.14', CNIL_URL),
  c('CNIL-13.1', 'Data processing agreement', 'Contrat de sous-traitance', 'A data processing agreement meeting RGPD Article 28 requirements shall be signed with each processor.', 'Un contrat de sous-traitance conforme a l\'article 28 du RGPD doit etre signe avec chaque sous-traitant.', 'Fiche 13 - Sous-traitance', null, '5.20', CNIL_URL),
  c('CNIL-13.2', 'Processor security audits', 'Audits de securite des sous-traitants', 'Processors shall be audited for compliance with security obligations at least annually.', 'Les sous-traitants doivent etre audites pour la conformite aux obligations de securite au moins annuellement.', 'Fiche 13 - Sous-traitance', null, '5.22', CNIL_URL),
  c('CNIL-14.1', 'Data transfer outside EU', 'Transfert de donnees hors UE', 'Transfers of personal data outside the EU shall be based on adequate safeguards per RGPD Chapter V.', 'Les transferts de donnees personnelles hors UE doivent etre fondes sur des garanties adequates selon le chapitre V du RGPD.', 'Fiche 14 - Securiser les echanges', null, null, CNIL_URL),
  c('CNIL-15.1', 'Visitor access control', 'Controle d\'acces des visiteurs', 'Visitors to premises with personal data processing equipment shall be escorted and logged.', 'Les visiteurs dans les locaux disposant d\'equipements de traitement de donnees personnelles doivent etre accompagnes et enregistres.', 'Fiche 15 - Proteger les locaux', null, '7.2', CNIL_URL),
  c('CNIL-16.1', 'Privacy by design', 'Protection de la vie privee des la conception', 'Data protection principles shall be integrated from the design phase of any new processing system.', 'Les principes de protection des donnees doivent etre integres des la phase de conception de tout nouveau systeme de traitement.', 'Fiche 16 - Developpements', null, '8.25', CNIL_URL),
  c('CNIL-16.2', 'Security testing before deployment', 'Tests de securite avant deploiement', 'Applications processing personal data shall undergo security testing before production deployment.', 'Les applications traitant des donnees personnelles doivent subir des tests de securite avant le deploiement en production.', 'Fiche 16 - Developpements', null, '8.29', CNIL_URL),
  c('CNIL-17.1', 'Password hashing', 'Hachage des mots de passe', 'Passwords shall be stored using approved hashing algorithms (bcrypt, scrypt, or Argon2).', 'Les mots de passe doivent etre stockes avec des algorithmes de hachage approuves (bcrypt, scrypt ou Argon2).', 'Fiche 17 - Chiffrer', null, '8.24', CNIL_URL),
  c('CNIL-17.2', 'Data at rest encryption', 'Chiffrement des donnees au repos', 'Sensitive personal data shall be encrypted at rest using AES-256 or equivalent.', 'Les donnees personnelles sensibles doivent etre chiffrees au repos avec AES-256 ou equivalent.', 'Fiche 17 - Chiffrer', null, '8.24', CNIL_URL),
];

// ============================================================
// PGSSI-S expansions
// ============================================================
const PGSSI_URL = 'https://esante.gouv.fr/produits-services/pgssi-s';
const pgssiExtra: Control[] = [
  c('PGSSI-IAM-04', 'National health identifier authentication', 'Authentification par identifiant national de sante', 'Health professionals shall authenticate using their CPS card or equivalent electronic certificate.', 'Les professionnels de sante doivent s\'authentifier avec leur carte CPS ou un certificat electronique equivalent.', 'Identification et authentification', null, '8.5', PGSSI_URL),
  c('PGSSI-IAM-05', 'Patient identity management', 'Gestion de l\'identite des patients', 'Patient identity shall be verified using INS (Identite Nationale de Sante) referential.', 'L\'identite du patient doit etre verifiee avec le referentiel INS (Identite Nationale de Sante).', 'Identification et authentification', null, '5.16', PGSSI_URL),
  c('PGSSI-IAM-06', 'Emergency access procedures', 'Procedures d\'acces d\'urgence', 'Emergency access procedures (bris de glace) shall allow temporary access to health data in life-threatening situations.', 'Les procedures d\'acces d\'urgence (bris de glace) doivent permettre un acces temporaire aux donnees de sante en situations de danger vital.', 'Identification et authentification', null, '5.18', PGSSI_URL),
  c('PGSSI-ACC-04', 'Consent management', 'Gestion du consentement', 'Patient consent for data access shall be recorded and verifiable in the information system.', 'Le consentement du patient pour l\'acces aux donnees doit etre enregistre et verifiable dans le systeme d\'information.', 'Gestion des droits d\'acces', null, '5.12', PGSSI_URL),
  c('PGSSI-ACC-05', 'Data access matrix', 'Matrice d\'acces aux donnees', 'A formal access matrix shall define which roles can access which categories of health data.', 'Une matrice d\'acces formelle doit definir quels roles peuvent acceder a quelles categories de donnees de sante.', 'Gestion des droits d\'acces', null, '5.15', PGSSI_URL),
  c('PGSSI-ACC-06', 'Temporary access management', 'Gestion des acces temporaires', 'Temporary access for locum professionals or trainees shall be time-limited and auditable.', 'L\'acces temporaire pour les remplacants ou stagiaires doit etre limite dans le temps et auditable.', 'Gestion des droits d\'acces', null, '5.18', PGSSI_URL),
  c('PGSSI-TRC-04', 'Audit trail for health records', 'Piste d\'audit pour les dossiers de sante', 'Every access to patient health records shall generate an immutable audit log entry.', 'Chaque acces aux dossiers de sante des patients doit generer une entree de journal d\'audit immuable.', 'Tracabilite', null, '8.15', PGSSI_URL),
  c('PGSSI-TRC-05', 'Patient access to audit logs', 'Acces du patient aux journaux d\'audit', 'Patients shall have the right to consult the log of access to their health data.', 'Les patients doivent avoir le droit de consulter le journal des acces a leurs donnees de sante.', 'Tracabilite', null, '8.15', PGSSI_URL),
  c('PGSSI-TRC-06', 'Audit log retention', 'Conservation des journaux d\'audit', 'Audit logs for health data access shall be retained for a minimum of 5 years.', 'Les journaux d\'audit des acces aux donnees de sante doivent etre conserves pendant un minimum de 5 ans.', 'Tracabilite', null, '5.33', PGSSI_URL),
  c('PGSSI-MSG-04', 'MSSante usage', 'Utilisation de MSSante', 'Health professionals shall use MSSante or equivalent approved messaging for electronic health data exchange.', 'Les professionnels de sante doivent utiliser MSSante ou une messagerie approuvee equivalente pour les echanges electroniques de donnees de sante.', 'Messageries securisees de sante', null, '5.14', PGSSI_URL),
  c('PGSSI-MSG-05', 'Messaging content protection', 'Protection du contenu des messageries', 'Health data exchanged via messaging shall be encrypted end-to-end and not stored on intermediate servers.', 'Les donnees de sante echangees par messagerie doivent etre chiffrees de bout en bout et non stockees sur des serveurs intermediaires.', 'Messageries securisees de sante', null, '8.24', PGSSI_URL),
  c('PGSSI-DAT-04', 'Health data classification', 'Classification des donnees de sante', 'Health data shall be classified by sensitivity level: standard, sensitive, and highly sensitive.', 'Les donnees de sante doivent etre classifiees par niveau de sensibilite : standard, sensible et hautement sensible.', 'Securite des donnees de sante', null, '5.12', PGSSI_URL),
  c('PGSSI-DAT-05', 'Pseudonymization of health data', 'Pseudonymisation des donnees de sante', 'Health data used for secondary purposes shall be pseudonymized using approved methods.', 'Les donnees de sante utilisees a des fins secondaires doivent etre pseudonymisees avec des methodes approuvees.', 'Securite des donnees de sante', null, '8.11', PGSSI_URL),
  c('PGSSI-DAT-06', 'Health data portability', 'Portabilite des donnees de sante', 'Patients shall be able to retrieve their health data in a structured, machine-readable format.', 'Les patients doivent pouvoir recuperer leurs donnees de sante dans un format structure et lisible par machine.', 'Securite des donnees de sante', null, null, PGSSI_URL),
  c('PGSSI-DAT-07', 'Backup of health data', 'Sauvegarde des donnees de sante', 'Health data shall be backed up regularly with encrypted backups stored in certified HDS facilities.', 'Les donnees de sante doivent etre sauvegardees regulierement avec des sauvegardes chiffrees stockees dans des etablissements HDS certifies.', 'Securite des donnees de sante', null, '8.13', PGSSI_URL),
  c('PGSSI-DAT-08', 'Interoperability standards', 'Normes d\'interoperabilite', 'Health data systems shall follow CI-SIS (Cadre d\'Interoperabilite des SIS) and HL7 FHIR standards.', 'Les systemes de donnees de sante doivent respecter les normes CI-SIS (Cadre d\'Interoperabilite des SIS) et HL7 FHIR.', 'Securite des donnees de sante', null, null, PGSSI_URL),
  c('PGSSI-DAT-09', 'Incident notification for health data', 'Notification des incidents pour les donnees de sante', 'Security incidents affecting health data shall be reported to ARS and CNIL within regulatory timeframes.', 'Les incidents de securite affectant les donnees de sante doivent etre signales a l\'ARS et la CNIL dans les delais reglementaires.', 'Securite des donnees de sante', null, '5.26', PGSSI_URL),
];

// ============================================================
// HDS expansions
// ============================================================
const HDS_URL = 'https://esante.gouv.fr/produits-services/hds';
const hdsExtra: Control[] = [
  c('HDS-INFRA-06', 'Data center location in France/EU', 'Localisation du centre de donnees en France/UE', 'Primary and backup data centers shall be located in France or the European Union.', 'Les centres de donnees principaux et de secours doivent etre situes en France ou dans l\'Union europeenne.', 'Infrastructure physique', null, null, HDS_URL),
  c('HDS-INFRA-07', 'Telecommunications redundancy', 'Redondance des telecommunications', 'Telecommunications connections shall be redundant with diverse physical paths.', 'Les connexions de telecommunications doivent etre redondantes avec des chemins physiques diversifies.', 'Infrastructure physique', null, '7.11', HDS_URL),
  c('HDS-NET-05', 'Network penetration testing', 'Tests d\'intrusion reseau', 'Network penetration tests shall be conducted at least annually by an independent PASSI-qualified auditor.', 'Des tests d\'intrusion reseau doivent etre conduits au moins annuellement par un auditeur PASSI qualifie independant.', 'Infrastructure reseau', null, '8.8', HDS_URL),
  c('HDS-NET-06', 'IDS/IPS deployment', 'Deploiement IDS/IPS', 'Intrusion detection and prevention systems shall monitor all network entry points.', 'Les systemes de detection et prevention d\'intrusion doivent surveiller tous les points d\'entree reseau.', 'Infrastructure reseau', null, '8.16', HDS_URL),
  c('HDS-MNG-05', 'Data return procedures', 'Procedures de restitution des donnees', 'Contract termination procedures shall guarantee complete return of health data to the client.', 'Les procedures de fin de contrat doivent garantir la restitution complete des donnees de sante au client.', 'Hebergement infogere', null, '5.20', HDS_URL),
  c('HDS-MNG-06', 'Data portability format', 'Format de portabilite des donnees', 'Health data shall be returnable in a standard, interoperable format (HL7 FHIR, CDA, CSV).', 'Les donnees de sante doivent etre restituables dans un format standard et interoperable (HL7 FHIR, CDA, CSV).', 'Hebergement infogere', null, null, HDS_URL),
  c('HDS-MNG-07', 'Secure data destruction at contract end', 'Destruction securisee des donnees en fin de contrat', 'All health data shall be securely destroyed after return, with certificate of destruction provided to client.', 'Toutes les donnees de sante doivent etre detruites de maniere securisee apres restitution, avec un certificat de destruction fourni au client.', 'Hebergement infogere', null, '7.14', HDS_URL),
  c('HDS-OPS-06', 'Access management for health data', 'Gestion des acces aux donnees de sante', 'Access to health data shall require named accounts with multi-factor authentication.', 'L\'acces aux donnees de sante doit necessiter des comptes nominatifs avec authentification multifacteur.', 'Infogrance d\'exploitation', null, '8.5', HDS_URL),
  c('HDS-OPS-07', 'Security monitoring and alerting', 'Surveillance et alerte de securite', 'Real-time security monitoring with defined alerting thresholds for health data infrastructure.', 'Surveillance de securite en temps reel avec des seuils d\'alerte definis pour l\'infrastructure de donnees de sante.', 'Infogrance d\'exploitation', null, '8.16', HDS_URL),
  c('HDS-OPS-08', 'Compliance reporting', 'Rapports de conformite', 'Monthly compliance reports shall be provided to clients covering availability, incidents, and security metrics.', 'Des rapports de conformite mensuels doivent etre fournis aux clients couvrant la disponibilite, les incidents et les metriques de securite.', 'Infogrance d\'exploitation', null, '5.36', HDS_URL),
  c('HDS-BCK-05', 'Cross-site backup replication', 'Replication de sauvegarde inter-sites', 'Backups shall be replicated to a secondary HDS-certified site for disaster recovery.', 'Les sauvegardes doivent etre repliquees vers un site secondaire certifie HDS pour la reprise apres sinistre.', 'Sauvegarde externalisee', null, '8.14', HDS_URL),
  c('HDS-CERT-04', 'ISO 27018 alignment', 'Alignement ISO 27018', 'HDS providers processing personal health data in the cloud shall align with ISO 27018 controls.', 'Les hebergeurs HDS traitant des donnees de sante personnelles dans le cloud doivent s\'aligner sur les controles ISO 27018.', 'Certification', null, null, HDS_URL),
  c('HDS-CERT-05', 'SOC 2 reporting', 'Rapports SOC 2', 'HDS providers shall make SOC 2 Type II reports available to clients upon request.', 'Les hebergeurs HDS doivent mettre les rapports SOC 2 Type II a disposition des clients sur demande.', 'Certification', null, '5.35', HDS_URL),
];

// Apply expansions
expand('anssi-secnumcloud.json', sncExtra);
expand('cnil-securite.json', cnilExtra);
expand('anssi-pgssi-s.json', pgssiExtra);
expand('hds.json', hdsExtra);

// Print totals
let total = 0;
for (const file of ['anssi-rgs.json', 'anssi-hygiene.json', 'anssi-secnumcloud.json', 'anssi-pgssi-s.json', 'cnil-securite.json', 'hds.json']) {
  const data = JSON.parse(readFileSync(join(DATA_DIR, file), 'utf-8'));
  const count = data.controls.length;
  total += count;
  console.log(`  ${file}: ${count}`);
}
console.log(`\nTotal controls: ${total}`);
