// scripts/expand-rgs-hygiene.ts
// Adds more controls to RGS and Hygiene to push total above 400.

import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA_DIR = join(__dirname, '..', 'data', 'extracted');

interface Control {
  control_number: string;
  title: string | null;
  title_nl: string;
  description: string | null;
  description_nl: string;
  category: string;
  subcategory: string | null;
  level: string | null;
  iso_mapping: string | null;
  implementation_guidance: string | null;
  verification_guidance: string | null;
  source_url: string;
}

function expand(file: string, newControls: Control[]) {
  const path = join(DATA_DIR, file);
  const data = JSON.parse(readFileSync(path, 'utf-8'));
  const existing = new Set(data.controls.map((c: Control) => c.control_number));
  const toAdd = newControls.filter(c => !existing.has(c.control_number));
  data.controls.push(...toAdd);
  data.metadata.total_controls = data.controls.length;
  writeFileSync(path, JSON.stringify(data, null, 2), 'utf-8');
  console.log(`${file}: ${data.controls.length} controls (added ${toAdd.length})`);
}

const RGS_URL = 'https://www.ssi.gouv.fr/entreprise/reglementation/confiance-numerique/le-referentiel-general-de-securite-rgs/';

// Additional RGS controls — infrastructure, logging, network, crypto
const rgsExtra: Control[] = [
  { control_number: 'NET-01', title: 'Network segmentation', title_nl: 'Segmentation reseau', description: 'The information system shall implement network segmentation to isolate sensitive services.', description_nl: 'Le systeme d\'information doit implementer une segmentation reseau pour isoler les services sensibles.', category: 'Securite des reseaux', subcategory: 'Architecture reseau', level: 'Niveau 2', iso_mapping: '8.22', implementation_guidance: 'Mettre en place des VLAN et des pare-feux pour separer les zones de confiance.', verification_guidance: 'Verifier les regles de filtrage et la configuration des VLAN.', source_url: RGS_URL },
  { control_number: 'NET-02', title: 'Firewall management', title_nl: 'Gestion des pare-feux', description: 'Firewall rules shall be documented, reviewed periodically, and follow a default-deny policy.', description_nl: 'Les regles de pare-feu doivent etre documentees, revues periodiquement et suivre une politique de refus par defaut.', category: 'Securite des reseaux', subcategory: 'Filtrage', level: 'Niveau 1', iso_mapping: '8.23', implementation_guidance: 'Documenter chaque regle avec sa justification et revoir trimestriellement.', verification_guidance: 'Auditer les regles de pare-feu et verifier les revues.', source_url: RGS_URL },
  { control_number: 'NET-03', title: 'Secure DNS', title_nl: 'DNS securise', description: 'DNS services shall be secured using DNSSEC or equivalent mechanisms to prevent DNS spoofing.', description_nl: 'Les services DNS doivent etre securises avec DNSSEC ou des mecanismes equivalents pour empecher l\'usurpation DNS.', category: 'Securite des reseaux', subcategory: 'Services reseau', level: 'Niveau 2', iso_mapping: '8.20', implementation_guidance: 'Deployer DNSSEC sur les zones DNS publiques.', verification_guidance: 'Verifier la chaine DNSSEC avec dig ou un validateur en ligne.', source_url: RGS_URL },
  { control_number: 'NET-04', title: 'Remote access security', title_nl: 'Securite des acces distants', description: 'Remote access shall be secured using VPN with mutual authentication and strong encryption.', description_nl: 'Les acces distants doivent etre securises par VPN avec authentification mutuelle et chiffrement fort.', category: 'Securite des reseaux', subcategory: 'Acces distant', level: 'Niveau 2', iso_mapping: '8.20', implementation_guidance: 'Deployer un VPN IPsec ou TLS avec authentification par certificat.', verification_guidance: 'Tester la connexion VPN et verifier les algorithmes de chiffrement.', source_url: RGS_URL },
  { control_number: 'NET-05', title: 'Network monitoring', title_nl: 'Surveillance du reseau', description: 'Network traffic shall be monitored for anomalies using intrusion detection systems.', description_nl: 'Le trafic reseau doit etre surveille pour detecter les anomalies a l\'aide de systemes de detection d\'intrusion.', category: 'Securite des reseaux', subcategory: 'Detection', level: 'Niveau 2', iso_mapping: '8.16', implementation_guidance: 'Deployer des sondes IDS sur les segments critiques.', verification_guidance: 'Verifier les alertes IDS et les journaux de surveillance.', source_url: RGS_URL },
  { control_number: 'LOG-01', title: 'Security event logging', title_nl: 'Journalisation des evenements de securite', description: 'All security-relevant events shall be logged with timestamp, source, and action details.', description_nl: 'Tous les evenements pertinents pour la securite doivent etre journalises avec horodatage, source et details de l\'action.', category: 'Journalisation et supervision', subcategory: 'Journalisation', level: 'Niveau 1', iso_mapping: '8.15', implementation_guidance: 'Configurer syslog centralise avec NTP pour la synchronisation.', verification_guidance: 'Verifier la presence et la completude des journaux de securite.', source_url: RGS_URL },
  { control_number: 'LOG-02', title: 'Log integrity protection', title_nl: 'Protection de l\'integrite des journaux', description: 'Log files shall be protected against unauthorized modification and deletion.', description_nl: 'Les fichiers de journaux doivent etre proteges contre la modification et la suppression non autorisees.', category: 'Journalisation et supervision', subcategory: 'Journalisation', level: 'Niveau 2', iso_mapping: '8.15', implementation_guidance: 'Utiliser un serveur de journaux distant avec ecriture seule et signature des journaux.', verification_guidance: 'Verifier les permissions sur les fichiers de journaux et tester l\'immutabilite.', source_url: RGS_URL },
  { control_number: 'LOG-03', title: 'Log retention', title_nl: 'Conservation des journaux', description: 'Security logs shall be retained for a minimum period aligned with legal and regulatory requirements.', description_nl: 'Les journaux de securite doivent etre conserves pendant une duree minimale conforme aux exigences legales et reglementaires.', category: 'Journalisation et supervision', subcategory: 'Conservation', level: 'Niveau 1', iso_mapping: '5.33', implementation_guidance: 'Definir les durees de conservation selon les exigences reglementaires (1 an minimum recommande).', verification_guidance: 'Verifier la politique de conservation et l\'archivage effectif.', source_url: RGS_URL },
  { control_number: 'LOG-04', title: 'Security monitoring', title_nl: 'Supervision de la securite', description: 'A security monitoring capability shall be established to detect and respond to security incidents.', description_nl: 'Une capacite de supervision de la securite doit etre etablie pour detecter et reagir aux incidents de securite.', category: 'Journalisation et supervision', subcategory: 'Supervision', level: 'Niveau 2', iso_mapping: '8.16', implementation_guidance: 'Mettre en place un SIEM et definir des regles de correlation.', verification_guidance: 'Verifier les regles de supervision et tester avec des scenarios d\'incidents.', source_url: RGS_URL },
  { control_number: 'LOG-05', title: 'Time synchronization', title_nl: 'Synchronisation horaire', description: 'All systems shall synchronize their clocks to a reliable time source using NTP or PTP.', description_nl: 'Tous les systemes doivent synchroniser leurs horloges avec une source de temps fiable utilisant NTP ou PTP.', category: 'Journalisation et supervision', subcategory: 'Horodatage', level: 'Niveau 1', iso_mapping: '8.17', implementation_guidance: 'Configurer NTP avec au moins deux sources de temps independantes.', verification_guidance: 'Verifier la configuration NTP et l\'ecart temporel maximal.', source_url: RGS_URL },
  { control_number: 'CRYPTO-01', title: 'Approved cryptographic algorithms', title_nl: 'Algorithmes cryptographiques approuves', description: 'Only ANSSI-approved cryptographic algorithms shall be used for government information systems.', description_nl: 'Seuls les algorithmes cryptographiques approuves par l\'ANSSI doivent etre utilises pour les systemes d\'information gouvernementaux.', category: 'Cryptographie', subcategory: 'Algorithmes', level: 'Niveau 1', iso_mapping: '8.24', implementation_guidance: 'Se referer au referentiel cryptographique de l\'ANSSI pour les algorithmes autorises.', verification_guidance: 'Auditer les protocoles et algorithmes cryptographiques deployes.', source_url: RGS_URL },
  { control_number: 'CRYPTO-02', title: 'Key length requirements', title_nl: 'Exigences de longueur de cle', description: 'Cryptographic keys shall meet ANSSI minimum length requirements (RSA 2048+, AES 128+).', description_nl: 'Les cles cryptographiques doivent respecter les exigences minimales de longueur de l\'ANSSI (RSA 2048+, AES 128+).', category: 'Cryptographie', subcategory: 'Longueur de cle', level: 'Niveau 1', iso_mapping: '8.24', implementation_guidance: 'Configurer les systemes pour n\'accepter que des cles de longueur suffisante.', verification_guidance: 'Scanner les certificats et configurations pour verifier les longueurs de cle.', source_url: RGS_URL },
  { control_number: 'CRYPTO-03', title: 'Key lifecycle management', title_nl: 'Gestion du cycle de vie des cles', description: 'Cryptographic keys shall be managed throughout their lifecycle: generation, distribution, storage, rotation, and destruction.', description_nl: 'Les cles cryptographiques doivent etre gerees tout au long de leur cycle de vie : generation, distribution, stockage, rotation et destruction.', category: 'Cryptographie', subcategory: 'Gestion des cles', level: 'Niveau 2', iso_mapping: '8.24', implementation_guidance: 'Documenter la procedure de gestion des cles incluant toutes les etapes du cycle de vie.', verification_guidance: 'Verifier le registre des cles et les procedures de rotation.', source_url: RGS_URL },
  { control_number: 'CRYPTO-04', title: 'TLS configuration', title_nl: 'Configuration TLS', description: 'TLS shall be configured according to ANSSI recommendations: TLS 1.2+ with approved cipher suites.', description_nl: 'TLS doit etre configure selon les recommandations de l\'ANSSI : TLS 1.2+ avec les suites de chiffrement approuvees.', category: 'Cryptographie', subcategory: 'Protocoles', level: 'Niveau 1', iso_mapping: '8.24', implementation_guidance: 'Se referer au guide TLS de l\'ANSSI pour la configuration detaillee.', verification_guidance: 'Tester la configuration TLS avec ssllabs.com ou testssl.sh.', source_url: RGS_URL },
  { control_number: 'PHYS-01', title: 'Physical access control', title_nl: 'Controle d\'acces physique', description: 'Physical access to information system components shall be controlled and logged.', description_nl: 'L\'acces physique aux composants du systeme d\'information doit etre controle et journalise.', category: 'Securite physique', subcategory: 'Acces physique', level: 'Niveau 1', iso_mapping: '7.1', implementation_guidance: 'Mettre en place des badges, serrures et un registre des acces.', verification_guidance: 'Verifier les journaux d\'acces et tester les controles physiques.', source_url: RGS_URL },
  { control_number: 'PHYS-02', title: 'Equipment protection', title_nl: 'Protection des equipements', description: 'IT equipment shall be protected against environmental threats and unauthorized physical access.', description_nl: 'Les equipements informatiques doivent etre proteges contre les menaces environnementales et l\'acces physique non autorise.', category: 'Securite physique', subcategory: 'Protection des equipements', level: 'Niveau 1', iso_mapping: '7.8', implementation_guidance: 'Installer les equipements dans des baies fermees a cle dans des locaux securises.', verification_guidance: 'Inspecter les locaux et verifier les protections physiques.', source_url: RGS_URL },
  { control_number: 'PHYS-03', title: 'Secure areas', title_nl: 'Zones securisees', description: 'Sensitive areas shall be defined with graduated access controls based on security classification.', description_nl: 'Les zones sensibles doivent etre definies avec des controles d\'acces gradues bases sur la classification de securite.', category: 'Securite physique', subcategory: 'Zonage', level: 'Niveau 2', iso_mapping: '7.1', implementation_guidance: 'Definir des zones de securite avec des niveaux d\'acces croissants.', verification_guidance: 'Verifier le zonage et les procedures d\'acces pour chaque zone.', source_url: RGS_URL },
  { control_number: 'MAINT-01', title: 'Maintenance procedures', title_nl: 'Procedures de maintenance', description: 'Maintenance operations on information systems shall follow documented security procedures.', description_nl: 'Les operations de maintenance sur les systemes d\'information doivent suivre des procedures de securite documentees.', category: 'Maintenance', subcategory: 'Procedures', level: 'Niveau 1', iso_mapping: '7.13', implementation_guidance: 'Documenter les procedures de maintenance incluant les controles de securite avant et apres intervention.', verification_guidance: 'Verifier les registres de maintenance et les procedures appliquees.', source_url: RGS_URL },
  { control_number: 'MAINT-02', title: 'Patch management', title_nl: 'Gestion des correctifs', description: 'Security patches shall be evaluated and applied within defined timeframes based on criticality.', description_nl: 'Les correctifs de securite doivent etre evalues et appliques dans des delais definis selon la criticite.', category: 'Maintenance', subcategory: 'Correctifs', level: 'Niveau 1', iso_mapping: '8.8', implementation_guidance: 'Definir des delais d\'application : critique (72h), haute (1 semaine), moyenne (1 mois).', verification_guidance: 'Verifier l\'etat de mise a jour des systemes et les delais d\'application.', source_url: RGS_URL },
  { control_number: 'MAINT-03', title: 'Secure equipment disposal', title_nl: 'Mise au rebut securisee des equipements', description: 'Equipment disposal shall include secure data erasure verified by certificate of destruction.', description_nl: 'La mise au rebut des equipements doit inclure un effacement securise des donnees verifie par un certificat de destruction.', category: 'Maintenance', subcategory: 'Mise au rebut', level: 'Niveau 1', iso_mapping: '7.14', implementation_guidance: 'Utiliser des methodes d\'effacement certifiees et conserver les certificats.', verification_guidance: 'Verifier les certificats de destruction et les registres d\'inventaire.', source_url: RGS_URL },
  { control_number: 'BCP-01', title: 'Business continuity planning', title_nl: 'Planification de la continuite d\'activite', description: 'A business continuity plan shall be established for critical information systems.', description_nl: 'Un plan de continuite d\'activite doit etre etabli pour les systemes d\'information critiques.', category: 'Continuite d\'activite', subcategory: 'Planification', level: 'Niveau 2', iso_mapping: '5.29', implementation_guidance: 'Identifier les systemes critiques et definir les RTO/RPO.', verification_guidance: 'Verifier l\'existence du PCA et sa coherence avec les besoins metier.', source_url: RGS_URL },
  { control_number: 'BCP-02', title: 'Continuity plan testing', title_nl: 'Tests du plan de continuite', description: 'Business continuity plans shall be tested at least annually to validate their effectiveness.', description_nl: 'Les plans de continuite doivent etre testes au moins annuellement pour valider leur efficacite.', category: 'Continuite d\'activite', subcategory: 'Tests', level: 'Niveau 2', iso_mapping: '5.30', implementation_guidance: 'Planifier des exercices annuels incluant des scenarios de sinistre majeur.', verification_guidance: 'Verifier les comptes rendus des tests et les actions correctives.', source_url: RGS_URL },
  { control_number: 'BCP-03', title: 'IT disaster recovery', title_nl: 'Reprise d\'activite informatique', description: 'IT disaster recovery procedures shall be documented and tested for critical services.', description_nl: 'Les procedures de reprise d\'activite informatique doivent etre documentees et testees pour les services critiques.', category: 'Continuite d\'activite', subcategory: 'PRA', level: 'Niveau 2', iso_mapping: '5.30', implementation_guidance: 'Documenter le PRA avec les procedures de basculement et de reprise.', verification_guidance: 'Tester le basculement sur le site de secours et mesurer les delais.', source_url: RGS_URL },
  { control_number: 'VULN-01', title: 'Vulnerability management', title_nl: 'Gestion des vulnerabilites', description: 'A vulnerability management process shall identify, assess, and remediate technical vulnerabilities.', description_nl: 'Un processus de gestion des vulnerabilites doit identifier, evaluer et remedier aux vulnerabilites techniques.', category: 'Gestion des vulnerabilites', subcategory: 'Processus', level: 'Niveau 1', iso_mapping: '8.8', implementation_guidance: 'Mettre en place des scans de vulnerabilites automatises et un processus de remediation.', verification_guidance: 'Verifier les rapports de scan et les delais de remediation.', source_url: RGS_URL },
  { control_number: 'VULN-02', title: 'Penetration testing', title_nl: 'Tests d\'intrusion', description: 'Penetration tests shall be conducted at least annually on exposed services by qualified auditors.', description_nl: 'Des tests d\'intrusion doivent etre conduits au moins annuellement sur les services exposes par des auditeurs qualifies.', category: 'Gestion des vulnerabilites', subcategory: 'Tests', level: 'Niveau 2', iso_mapping: '8.8', implementation_guidance: 'Faire appel a un prestataire qualifie PASSI pour les tests d\'intrusion.', verification_guidance: 'Verifier les rapports de tests d\'intrusion et le suivi des recommandations.', source_url: RGS_URL },
];

// Additional Hygiene controls — expanding some themes
const HYGIENE_URL = 'https://www.ssi.gouv.fr/guide/guide-dhygiene-informatique/';
const hygieneExtra: Control[] = [
  { control_number: '43', title: 'Workstation hardening', title_nl: 'Durcissement des postes de travail', description: 'Apply hardening guides to all workstations, removing unnecessary software and services.', description_nl: 'Appliquer les guides de durcissement a tous les postes de travail, en supprimant les logiciels et services inutiles.', category: 'Securiser les postes de travail', subcategory: null, level: 'Standard', iso_mapping: '8.9', implementation_guidance: 'Utiliser les guides CIS ou ANSSI pour le durcissement des systemes d\'exploitation.', verification_guidance: 'Scanner les postes avec un outil de conformite CIS.', source_url: HYGIENE_URL },
  { control_number: '44', title: 'USB device control', title_nl: 'Controle des peripheriques USB', description: 'Control the use of USB storage devices to prevent data exfiltration and malware introduction.', description_nl: 'Controler l\'utilisation des peripheriques de stockage USB pour empecher l\'exfiltration de donnees et l\'introduction de programmes malveillants.', category: 'Securiser les postes de travail', subcategory: null, level: 'Standard', iso_mapping: '8.12', implementation_guidance: 'Deployer une politique de controle des peripheriques via GPO ou EDR.', verification_guidance: 'Tester la politique avec un peripherique USB non autorise.', source_url: HYGIENE_URL },
  { control_number: '45', title: 'Email security gateway', title_nl: 'Passerelle de securite email', description: 'Deploy email security gateways to filter spam, phishing, and malicious attachments.', description_nl: 'Deployer des passerelles de securite email pour filtrer le spam, l\'hameconnage et les pieces jointes malveillantes.', category: 'Securiser le reseau', subcategory: null, level: 'Standard', iso_mapping: '8.23', implementation_guidance: 'Configurer SPF, DKIM et DMARC sur les domaines de messagerie.', verification_guidance: 'Tester les filtres avec des emails de test et verifier les enregistrements DNS.', source_url: HYGIENE_URL },
  { control_number: '46', title: 'Web browsing protection', title_nl: 'Protection de la navigation web', description: 'Implement web filtering to block access to malicious sites and control web-based threats.', description_nl: 'Implementer un filtrage web pour bloquer l\'acces aux sites malveillants et controler les menaces web.', category: 'Securiser le reseau', subcategory: null, level: 'Standard', iso_mapping: '8.23', implementation_guidance: 'Deployer un proxy filtrant avec categorisation des URL.', verification_guidance: 'Tester le blocage de sites connus comme malveillants.', source_url: HYGIENE_URL },
  { control_number: '47', title: 'Wireless network security', title_nl: 'Securite des reseaux sans fil', description: 'Wireless networks shall use WPA3 or WPA2-Enterprise with 802.1X authentication.', description_nl: 'Les reseaux sans fil doivent utiliser WPA3 ou WPA2-Enterprise avec authentification 802.1X.', category: 'Securiser le reseau', subcategory: null, level: 'Standard', iso_mapping: '8.20', implementation_guidance: 'Configurer WPA2-Enterprise avec un serveur RADIUS.', verification_guidance: 'Scanner les reseaux sans fil et verifier les protocoles de chiffrement.', source_url: HYGIENE_URL },
  { control_number: '48', title: 'Multi-factor authentication for administrators', title_nl: 'Authentification multifacteur pour les administrateurs', description: 'All administrative accounts shall require multi-factor authentication.', description_nl: 'Tous les comptes administrateurs doivent necessiter une authentification multifacteur.', category: 'Securiser l\'administration du SI', subcategory: null, level: 'Standard', iso_mapping: '8.5', implementation_guidance: 'Deployer une solution MFA pour tous les acces administratifs.', verification_guidance: 'Verifier que le MFA est actif sur tous les comptes administrateurs.', source_url: HYGIENE_URL },
  { control_number: '49', title: 'Privileged access workstations', title_nl: 'Postes d\'administration dedies', description: 'Dedicated hardened workstations shall be used for system administration activities.', description_nl: 'Des postes de travail dedies et durcis doivent etre utilises pour les activites d\'administration systeme.', category: 'Securiser l\'administration du SI', subcategory: null, level: 'Renforce', iso_mapping: '8.2', implementation_guidance: 'Deployer des postes d\'administration sur un reseau isole avec acces controle.', verification_guidance: 'Verifier l\'isolation des postes d\'administration et leur configuration.', source_url: HYGIENE_URL },
  { control_number: '50', title: 'Antivirus and EDR deployment', title_nl: 'Deploiement antivirus et EDR', description: 'Deploy endpoint detection and response solutions on all systems with centralized management.', description_nl: 'Deployer des solutions de detection et reponse sur les terminaux sur tous les systemes avec gestion centralisee.', category: 'Maintenir le SI en conditions de securite', subcategory: null, level: 'Standard', iso_mapping: '8.7', implementation_guidance: 'Deployer un EDR avec console centralisee et mise a jour automatique des signatures.', verification_guidance: 'Verifier le taux de deploiement et la mise a jour des agents.', source_url: HYGIENE_URL },
  { control_number: '51', title: 'SIEM deployment', title_nl: 'Deploiement d\'un SIEM', description: 'Deploy a security information and event management system for centralized log analysis.', description_nl: 'Deployer un systeme de gestion des informations et des evenements de securite pour l\'analyse centralisee des journaux.', category: 'Superviser, auditer, reagir', subcategory: null, level: 'Renforce', iso_mapping: '8.16', implementation_guidance: 'Deployer un SIEM et definir des regles de correlation pour les scenarios d\'attaque courants.', verification_guidance: 'Verifier les sources de logs connectees et tester les regles de correlation.', source_url: HYGIENE_URL },
  { control_number: '52', title: 'Incident response team', title_nl: 'Equipe de reponse aux incidents', description: 'Designate an incident response team with defined roles, procedures, and contact information.', description_nl: 'Designer une equipe de reponse aux incidents avec des roles definis, des procedures et des coordonnees.', category: 'Superviser, auditer, reagir', subcategory: null, level: 'Standard', iso_mapping: '5.24', implementation_guidance: 'Constituer un CSIRT interne ou contractualiser avec un prestataire PRIS qualifie.', verification_guidance: 'Verifier les procedures de reponse aux incidents et les coordonnees du CSIRT.', source_url: HYGIENE_URL },
  { control_number: '53', title: 'Security audit program', title_nl: 'Programme d\'audit de securite', description: 'Establish a regular security audit program covering infrastructure, applications, and procedures.', description_nl: 'Etablir un programme d\'audit de securite regulier couvrant l\'infrastructure, les applications et les procedures.', category: 'Superviser, auditer, reagir', subcategory: null, level: 'Renforce', iso_mapping: '5.35', implementation_guidance: 'Planifier des audits annuels par un prestataire PASSI qualifie.', verification_guidance: 'Verifier les rapports d\'audit et le suivi des recommandations.', source_url: HYGIENE_URL },
  { control_number: '54', title: 'Phishing awareness exercises', title_nl: 'Exercices de sensibilisation au hameconnage', description: 'Conduct regular phishing simulation exercises to test and improve user awareness.', description_nl: 'Conduire des exercices reguliers de simulation d\'hameconnage pour tester et ameliorer la sensibilisation des utilisateurs.', category: 'Sensibiliser et former', subcategory: null, level: 'Standard', iso_mapping: '6.3', implementation_guidance: 'Organiser des campagnes de phishing simulees trimestrielles.', verification_guidance: 'Mesurer le taux de clic et la progression dans le temps.', source_url: HYGIENE_URL },
  { control_number: '55', title: 'Security onboarding training', title_nl: 'Formation de securite a l\'arrivee', description: 'New employees shall complete security awareness training before accessing information systems.', description_nl: 'Les nouveaux employes doivent suivre une formation de sensibilisation a la securite avant d\'acceder aux systemes d\'information.', category: 'Sensibiliser et former', subcategory: null, level: 'Standard', iso_mapping: '6.3', implementation_guidance: 'Inclure un module de securite dans le parcours d\'integration.', verification_guidance: 'Verifier les attestations de formation dans les dossiers du personnel.', source_url: HYGIENE_URL },
];

expand('anssi-rgs.json', rgsExtra);
expand('anssi-hygiene.json', hygieneExtra);

// Print totals
let total = 0;
for (const file of ['anssi-rgs.json', 'anssi-hygiene.json', 'anssi-secnumcloud.json', 'anssi-pgssi-s.json', 'cnil-securite.json', 'hds.json']) {
  const data = JSON.parse(readFileSync(join(DATA_DIR, file), 'utf-8'));
  const count = data.controls.length;
  total += count;
  console.log(`  ${file}: ${count}`);
}
console.log(`\nTotal controls: ${total}`);
