// scripts/ingest-anssi-hygiene.ts
// Generates ANSSI Guide d'hygiene informatique (42 measures) controls.
// Source: https://www.ssi.gouv.fr/guide/guide-dhygiene-informatique/

import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA_DIR = join(__dirname, '..', 'data', 'extracted');
const OUTPUT_FILE = join(DATA_DIR, 'anssi-hygiene.json');

interface Control {
  control_number: string;
  title: string | null;
  title_nl: string;
  description: string | null;
  description_nl: string;
  category: string;
  subcategory: string | null;
  level: string | null;
  iso_mapping: string | null;
  implementation_guidance: string | null;
  verification_guidance: string | null;
  source_url: string;
}

const SOURCE_URL = 'https://www.ssi.gouv.fr/guide/guide-dhygiene-informatique/';

const controls: Control[] = [
  // Theme 1: Connaitre le SI (Know your IS)
  { control_number: '1', title: 'Map the information system', title_nl: 'Cartographier le systeme d\'information', description: 'Maintain an up-to-date map of the information system including hardware, software, network architecture, and data flows.', description_nl: 'Maintenir une cartographie a jour du systeme d\'information incluant les equipements, logiciels, architecture reseau et flux de donnees.', category: 'Connaitre le systeme d\'information', subcategory: null, level: 'Standard', iso_mapping: '5.9', implementation_guidance: 'Inventorier l\'ensemble des equipements, serveurs, postes de travail, equipements reseau. Documenter l\'architecture reseau et les flux de donnees.', verification_guidance: 'Verifier l\'existence et l\'actualite de la cartographie du SI.', source_url: SOURCE_URL },
  { control_number: '2', title: 'Map the Active Directory', title_nl: 'Cartographier l\'Active Directory', description: 'Map the Active Directory or identity directory: organizational units, groups, group policies, trust relationships, and privileged accounts.', description_nl: 'Cartographier l\'Active Directory ou l\'annuaire d\'identites : unites organisationnelles, groupes, strategies de groupe, relations d\'approbation et comptes privilegies.', category: 'Connaitre le systeme d\'information', subcategory: null, level: 'Standard', iso_mapping: '5.16', implementation_guidance: 'Documenter la structure de l\'annuaire, les groupes de securite, les GPO appliquees et les comptes a privileges.', verification_guidance: 'Verifier que la cartographie de l\'annuaire est documentee et a jour.', source_url: SOURCE_URL },
  { control_number: '3', title: 'Maintain a hardware and software inventory', title_nl: 'Maintenir un inventaire des materiels et logiciels', description: 'Maintain a complete and up-to-date inventory of all hardware and software, including versions and patch levels.', description_nl: 'Maintenir un inventaire complet et a jour de l\'ensemble des materiels et logiciels, incluant les versions et niveaux de correctifs.', category: 'Connaitre le systeme d\'information', subcategory: null, level: 'Standard', iso_mapping: '5.9', implementation_guidance: 'Utiliser des outils d\'inventaire automatise. Suivre les versions de logiciels et leur niveau de mise a jour.', verification_guidance: 'Verifier la completude de l\'inventaire par echantillonnage.', source_url: SOURCE_URL },
  { control_number: '4', title: 'Conduct regular risk analyses', title_nl: 'Mener des analyses de risques regulieres', description: 'Conduct risk analyses on the information system using a recognized methodology and update them after significant changes.', description_nl: 'Conduire des analyses de risques sur le systeme d\'information en utilisant une methodologie reconnue et les mettre a jour apres les changements significatifs.', category: 'Connaitre le systeme d\'information', subcategory: null, level: 'Standard', iso_mapping: '5.1', implementation_guidance: 'Utiliser EBIOS Risk Manager ou une methodologie equivalente. Revoir l\'analyse apres chaque changement majeur du SI.', verification_guidance: 'Verifier la realisation et l\'actualite des analyses de risques.', source_url: SOURCE_URL },
  { control_number: '5', title: 'Define and apply a classification policy', title_nl: 'Definir et appliquer une politique de classification', description: 'Define a data classification policy and apply it to identify and protect sensitive information appropriately.', description_nl: 'Definir une politique de classification des donnees et l\'appliquer pour identifier et proteger les informations sensibles de maniere appropriee.', category: 'Connaitre le systeme d\'information', subcategory: null, level: 'Standard', iso_mapping: '5.12', implementation_guidance: 'Definir les niveaux de classification (public, interne, confidentiel, secret). Former les utilisateurs au marquage des documents.', verification_guidance: 'Verifier l\'application de la classification par echantillonnage de documents.', source_url: SOURCE_URL },

  // Theme 2: Maitriser les acces (Control access)
  { control_number: '6', title: 'Assign unique identifiers to each user', title_nl: 'Attribuer un identifiant unique a chaque utilisateur', description: 'Each user shall have a unique personal identifier. Generic or shared accounts shall be prohibited except where technically unavoidable.', description_nl: 'Chaque utilisateur doit disposer d\'un identifiant personnel unique. Les comptes generiques ou partages doivent etre interdits sauf lorsque c\'est techniquement inevitable.', category: 'Maitriser les acces', subcategory: null, level: 'Standard', iso_mapping: '5.16', implementation_guidance: 'Attribuer des identifiants nominatifs. Supprimer ou desactiver les comptes generiques. Documenter les exceptions.', verification_guidance: 'Lister les comptes et verifier l\'absence de comptes generiques non documentes.', source_url: SOURCE_URL },
  { control_number: '7', title: 'Use strong authentication where required', title_nl: 'Utiliser une authentification forte lorsque necessaire', description: 'Deploy multi-factor authentication for access to sensitive systems, remote access, and administrator accounts.', description_nl: 'Deployer l\'authentification multifacteur pour l\'acces aux systemes sensibles, l\'acces a distance et les comptes administrateurs.', category: 'Maitriser les acces', subcategory: null, level: 'Renforce', iso_mapping: '8.5', implementation_guidance: 'Deployer le MFA pour les VPN, les acces d\'administration et les applications contenant des donnees sensibles.', verification_guidance: 'Verifier le deploiement du MFA sur les perimtres identifies.', source_url: SOURCE_URL },
  { control_number: '8', title: 'Apply a strict password policy', title_nl: 'Appliquer une politique de mots de passe stricte', description: 'Implement a password policy covering minimum length, complexity, renewal, and storage in compliance with ANSSI recommendations.', description_nl: 'Mettre en oeuvre une politique de mots de passe couvrant la longueur minimale, la complexite, le renouvellement et le stockage conformement aux recommandations ANSSI.', category: 'Maitriser les acces', subcategory: null, level: 'Standard', iso_mapping: '5.17', implementation_guidance: 'Configurer les exigences de mots de passe dans l\'annuaire. Interdire les mots de passe faibles. Stocker les empreintes de maniere securisee.', verification_guidance: 'Tester la politique de mots de passe par audit technique.', source_url: SOURCE_URL },
  { control_number: '9', title: 'Implement least privilege access', title_nl: 'Mettre en oeuvre le moindre privilege', description: 'Grant users only the minimum access rights required for their role. Review access rights regularly.', description_nl: 'Accorder aux utilisateurs uniquement les droits d\'acces minimaux necessaires a leur role. Reviser regulierement les droits d\'acces.', category: 'Maitriser les acces', subcategory: null, level: 'Standard', iso_mapping: '5.18', implementation_guidance: 'Definir des profils de droits par role metier. Reviser les droits trimestriellement. Supprimer les droits des collaborateurs partis.', verification_guidance: 'Conduire une revue des droits d\'acces et identifier les anomalies.', source_url: SOURCE_URL },
  { control_number: '10', title: 'Disable unused accounts', title_nl: 'Desactiver les comptes inutilises', description: 'Disable or remove user accounts that are no longer needed, including accounts of departed employees and dormant accounts.', description_nl: 'Desactiver ou supprimer les comptes utilisateurs qui ne sont plus necessaires, incluant les comptes des employes partis et les comptes dormants.', category: 'Maitriser les acces', subcategory: null, level: 'Standard', iso_mapping: '5.18', implementation_guidance: 'Mettre en place un processus automatise de desactivation des comptes lies aux departs. Identifier et desactiver les comptes dormants (inactifs depuis 90 jours).', verification_guidance: 'Lister les comptes inactifs et verifier leur desactivation.', source_url: SOURCE_URL },
  { control_number: '11', title: 'Protect administrator accounts', title_nl: 'Proteger les comptes d\'administration', description: 'Administrator accounts shall be strictly controlled: dedicated accounts, strong authentication, limited use, and enhanced monitoring.', description_nl: 'Les comptes d\'administration doivent etre strictement controles : comptes dedies, authentification forte, utilisation limitee et surveillance renforcee.', category: 'Maitriser les acces', subcategory: null, level: 'Renforce', iso_mapping: '8.2', implementation_guidance: 'Creer des comptes d\'administration dedies (pas d\'usage quotidien). Appliquer le MFA. Journaliser toutes les actions d\'administration.', verification_guidance: 'Verifier la separation des comptes d\'administration et des comptes utilisateurs.', source_url: SOURCE_URL },
  { control_number: '12', title: 'Manage access rights upon arrival, change, and departure', title_nl: 'Gerer les droits d\'acces aux arrivees, mutations et departs', description: 'Formal procedures shall manage access rights throughout the employee lifecycle: onboarding, role changes, and offboarding.', description_nl: 'Des procedures formelles doivent gerer les droits d\'acces tout au long du cycle de vie de l\'employe : arrivee, changement de poste et depart.', category: 'Maitriser les acces', subcategory: null, level: 'Standard', iso_mapping: '5.18', implementation_guidance: 'Definir un processus RH-SI pour l\'attribution et la revocation des droits. Automatiser lorsque possible.', verification_guidance: 'Verifier les delais de creation et revocation des comptes par echantillonnage.', source_url: SOURCE_URL },
  { control_number: '13', title: 'Control physical access to server rooms', title_nl: 'Controler l\'acces physique aux salles serveur', description: 'Physical access to server rooms and network equipment shall be restricted to authorized personnel only.', description_nl: 'L\'acces physique aux salles serveur et aux equipements reseau doit etre restreint au seul personnel autorise.', category: 'Maitriser les acces', subcategory: null, level: 'Standard', iso_mapping: '7.2', implementation_guidance: 'Installer des controles d\'acces physiques (badges, biometrie). Tenir un registre des acces. Surveiller par videosurveillance.', verification_guidance: 'Inspecter les dispositifs de controle d\'acces et les registres.', source_url: SOURCE_URL },

  // Theme 3: Securiser les postes (Secure workstations)
  { control_number: '14', title: 'Deploy a host firewall on all workstations', title_nl: 'Deployer un pare-feu local sur tous les postes de travail', description: 'Enable and configure the host firewall on all workstations to restrict incoming and outgoing connections.', description_nl: 'Activer et configurer le pare-feu local sur tous les postes de travail pour restreindre les connexions entrantes et sortantes.', category: 'Securiser les postes', subcategory: null, level: 'Standard', iso_mapping: '8.1', implementation_guidance: 'Activer le pare-feu Windows ou equivalent. Bloquer les connexions entrantes par defaut. Autoriser uniquement les flux necessaires.', verification_guidance: 'Verifier l\'activation et la configuration du pare-feu sur un echantillon de postes.', source_url: SOURCE_URL },
  { control_number: '15', title: 'Encrypt workstation storage', title_nl: 'Chiffrer le stockage des postes de travail', description: 'Enable full-disk encryption on all workstations to protect data in case of loss or theft.', description_nl: 'Activer le chiffrement integral du disque sur tous les postes de travail pour proteger les donnees en cas de perte ou vol.', category: 'Securiser les postes', subcategory: null, level: 'Renforce', iso_mapping: '8.24', implementation_guidance: 'Deployer BitLocker (Windows) ou equivalent. Centraliser la gestion des cles de recouvrement.', verification_guidance: 'Verifier l\'activation du chiffrement sur un echantillon de postes.', source_url: SOURCE_URL },
  { control_number: '16', title: 'Keep software up to date', title_nl: 'Maintenir les logiciels a jour', description: 'Deploy operating system and application security patches within the timeline appropriate to their criticality.', description_nl: 'Deployer les correctifs de securite du systeme d\'exploitation et des applications dans les delais adaptes a leur criticite.', category: 'Securiser les postes', subcategory: null, level: 'Standard', iso_mapping: '8.8', implementation_guidance: 'Mettre en place un outil de deploiement de correctifs (WSUS, SCCM ou equivalent). Prioriser les correctifs critiques.', verification_guidance: 'Mesurer le taux de postes a jour et les delais de deploiement.', source_url: SOURCE_URL },
  { control_number: '17', title: 'Install and maintain antivirus protection', title_nl: 'Installer et maintenir une protection antivirale', description: 'Deploy and maintain antivirus or endpoint protection on all workstations with automatic signature updates.', description_nl: 'Deployer et maintenir un antivirus ou une protection endpoint sur tous les postes de travail avec mise a jour automatique des signatures.', category: 'Securiser les postes', subcategory: null, level: 'Standard', iso_mapping: '8.7', implementation_guidance: 'Deployer un EDR ou antivirus gere centralement. Configurer les mises a jour automatiques. Surveiller les alertes.', verification_guidance: 'Verifier le deploiement et la mise a jour de la protection antivirale.', source_url: SOURCE_URL },
  { control_number: '18', title: 'Restrict software installation to authorized software', title_nl: 'Restreindre l\'installation de logiciels aux logiciels autorises', description: 'Users shall not be allowed to install software without authorization. Use application whitelisting where possible.', description_nl: 'Les utilisateurs ne doivent pas etre autorises a installer de logiciels sans autorisation. Utiliser le whitelisting applicatif lorsque possible.', category: 'Securiser les postes', subcategory: null, level: 'Renforce', iso_mapping: '8.19', implementation_guidance: 'Retirer les droits d\'administration locale. Mettre en place un catalogue de logiciels autorises et un processus de demande.', verification_guidance: 'Verifier les droits locaux et l\'application du whitelisting.', source_url: SOURCE_URL },

  // Theme 4: Securiser le reseau (Secure the network)
  { control_number: '19', title: 'Segment the network', title_nl: 'Segmenter le reseau', description: 'Segment the network into security zones based on sensitivity levels and business requirements.', description_nl: 'Segmenter le reseau en zones de securite basees sur les niveaux de sensibilite et les besoins metier.', category: 'Securiser le reseau', subcategory: null, level: 'Standard', iso_mapping: '8.22', implementation_guidance: 'Definir des zones de securite (serveurs, postes, DMZ, administration). Filtrer les flux entre zones avec des pare-feux.', verification_guidance: 'Verifier la segmentation reseau et les regles de filtrage.', source_url: SOURCE_URL },
  { control_number: '20', title: 'Secure Wi-Fi access', title_nl: 'Securiser les acces Wi-Fi', description: 'Wi-Fi networks shall use WPA3 or WPA2-Enterprise with RADIUS authentication. Separate guest networks from internal networks.', description_nl: 'Les reseaux Wi-Fi doivent utiliser WPA3 ou WPA2-Enterprise avec authentification RADIUS. Separer les reseaux invites des reseaux internes.', category: 'Securiser le reseau', subcategory: null, level: 'Standard', iso_mapping: '8.20', implementation_guidance: 'Deployer WPA2-Enterprise minimum (802.1X). Isoler le reseau Wi-Fi invites. Desactiver WPS.', verification_guidance: 'Auditer la configuration Wi-Fi et la separation des reseaux.', source_url: SOURCE_URL },
  { control_number: '21', title: 'Protect interconnections with the Internet', title_nl: 'Proteger les interconnexions avec Internet', description: 'Internet connections shall be secured through firewalls, web proxies, and intrusion detection systems.', description_nl: 'Les connexions Internet doivent etre securisees par des pare-feux, proxies web et systemes de detection d\'intrusion.', category: 'Securiser le reseau', subcategory: null, level: 'Standard', iso_mapping: '8.20', implementation_guidance: 'Deployer un pare-feu de nouvelle generation en peripherie. Utiliser un proxy web filtrant. Mettre en place un IDS/IPS.', verification_guidance: 'Auditer les regles de pare-feu et la configuration du proxy.', source_url: SOURCE_URL },
  { control_number: '22', title: 'Secure remote access', title_nl: 'Securiser les acces a distance', description: 'Remote access shall use encrypted VPN connections with strong authentication.', description_nl: 'Les acces a distance doivent utiliser des connexions VPN chiffrees avec authentification forte.', category: 'Securiser le reseau', subcategory: null, level: 'Standard', iso_mapping: '8.20', implementation_guidance: 'Deployer un VPN avec chiffrement conforme aux recommandations ANSSI. Imposer l\'authentification multifacteur pour le VPN.', verification_guidance: 'Verifier la configuration VPN et l\'application du MFA.', source_url: SOURCE_URL },
  { control_number: '23', title: 'Use TLS for all web services', title_nl: 'Utiliser TLS pour tous les services web', description: 'All web services shall use TLS 1.2 or higher with cipher suites compliant with ANSSI recommendations.', description_nl: 'Tous les services web doivent utiliser TLS 1.2 ou superieur avec des suites de chiffrement conformes aux recommandations ANSSI.', category: 'Securiser le reseau', subcategory: null, level: 'Standard', iso_mapping: '8.24', implementation_guidance: 'Configurer TLS 1.2 minimum (TLS 1.3 recommande). Desactiver les suites de chiffrement obsoletes. Utiliser des certificats valides.', verification_guidance: 'Scanner les services web pour verifier les configurations TLS.', source_url: SOURCE_URL },

  // Theme 5: Securiser l'administration (Secure administration)
  { control_number: '24', title: 'Dedicate administration accounts', title_nl: 'Dedier les comptes d\'administration', description: 'Use dedicated accounts for administration tasks, separate from day-to-day user accounts.', description_nl: 'Utiliser des comptes dedies pour les taches d\'administration, separes des comptes utilisateurs quotidiens.', category: 'Securiser l\'administration', subcategory: null, level: 'Standard', iso_mapping: '8.2', implementation_guidance: 'Creer des comptes d\'administration distincts des comptes bureautiques. Interdire la navigation Internet depuis les comptes d\'administration.', verification_guidance: 'Verifier la separation des comptes d\'administration.', source_url: SOURCE_URL },
  { control_number: '25', title: 'Use a dedicated administration network', title_nl: 'Utiliser un reseau d\'administration dedie', description: 'Administration traffic shall flow through a dedicated and isolated network, separate from user networks.', description_nl: 'Le trafic d\'administration doit transiter par un reseau dedie et isole, separe des reseaux utilisateurs.', category: 'Securiser l\'administration', subcategory: null, level: 'Renforce', iso_mapping: '8.22', implementation_guidance: 'Deployer un VLAN ou reseau physique dedie a l\'administration. Restreindre l\'acces aux equipements d\'administration depuis ce reseau uniquement.', verification_guidance: 'Verifier l\'isolation du reseau d\'administration.', source_url: SOURCE_URL },
  { control_number: '26', title: 'Harden administration workstations', title_nl: 'Durcir les postes d\'administration', description: 'Administration workstations shall be hardened: minimal software, no Internet access, dedicated to administration tasks only.', description_nl: 'Les postes d\'administration doivent etre durcis : logiciels minimaux, pas d\'acces Internet, dedies uniquement aux taches d\'administration.', category: 'Securiser l\'administration', subcategory: null, level: 'Renforce', iso_mapping: '8.1', implementation_guidance: 'Deployer des postes d\'administration durcis sans acces Internet direct. Installer uniquement les outils d\'administration necessaires.', verification_guidance: 'Inspecter la configuration des postes d\'administration.', source_url: SOURCE_URL },
  { control_number: '27', title: 'Secure administration protocols', title_nl: 'Securiser les protocoles d\'administration', description: 'Use only encrypted protocols for remote administration (SSH, HTTPS, RDP over TLS). Disable unencrypted protocols (Telnet, HTTP, SNMPv1/v2).', description_nl: 'Utiliser uniquement des protocoles chiffres pour l\'administration a distance (SSH, HTTPS, RDP sur TLS). Desactiver les protocoles non chiffres (Telnet, HTTP, SNMPv1/v2).', category: 'Securiser l\'administration', subcategory: null, level: 'Standard', iso_mapping: '8.20', implementation_guidance: 'Desactiver Telnet, HTTP non securise et SNMPv1/v2 sur tous les equipements. Configurer SSH avec des algorithmes conformes ANSSI.', verification_guidance: 'Scanner les services exposes pour verifier l\'absence de protocoles non chiffres.', source_url: SOURCE_URL },
  { control_number: '28', title: 'Trace and audit administration actions', title_nl: 'Tracer et auditer les actions d\'administration', description: 'All administration actions shall be logged in a centralized and tamper-proof logging system.', description_nl: 'Toutes les actions d\'administration doivent etre journalisees dans un systeme de journalisation centralise et infalsifiable.', category: 'Securiser l\'administration', subcategory: null, level: 'Standard', iso_mapping: '8.15', implementation_guidance: 'Centraliser les journaux d\'administration dans un SIEM. Proteger l\'integrite des journaux. Definir des regles d\'alerte.', verification_guidance: 'Verifier la centralisation et l\'integrite des journaux d\'administration.', source_url: SOURCE_URL },

  // Theme 6: Maintenir en conditions de securite (Maintain security)
  { control_number: '29', title: 'Define a patch management policy', title_nl: 'Definir une politique de gestion des correctifs', description: 'Establish a formal patch management policy defining timelines for applying patches based on their criticality.', description_nl: 'Etablir une politique formelle de gestion des correctifs definissant les delais d\'application des correctifs en fonction de leur criticite.', category: 'Maintenir en conditions de securite', subcategory: null, level: 'Standard', iso_mapping: '8.8', implementation_guidance: 'Definir les delais : critique (48h), haute (7 jours), moyenne (30 jours). Tester les correctifs avant deploiement.', verification_guidance: 'Mesurer le respect des delais de deploiement des correctifs.', source_url: SOURCE_URL },
  { control_number: '30', title: 'Monitor security advisories', title_nl: 'Surveiller les avis de securite', description: 'Monitor security advisories from CERT-FR, vendors, and relevant CERTs to identify vulnerabilities affecting the information system.', description_nl: 'Surveiller les avis de securite du CERT-FR, des editeurs et des CERT pertinents pour identifier les vulnerabilites affectant le systeme d\'information.', category: 'Maintenir en conditions de securite', subcategory: null, level: 'Standard', iso_mapping: '5.7', implementation_guidance: 'S\'abonner aux alertes du CERT-FR. Suivre les avis de securite des editeurs. Evaluer l\'applicabilite au SI.', verification_guidance: 'Verifier le processus de veille et le delai de traitement des alertes.', source_url: SOURCE_URL },
  { control_number: '31', title: 'Manage end-of-life software', title_nl: 'Gerer les logiciels en fin de vie', description: 'Identify and plan the replacement of software that has reached end of support and no longer receives security updates.', description_nl: 'Identifier et planifier le remplacement des logiciels ayant atteint la fin de support et ne recevant plus de mises a jour de securite.', category: 'Maintenir en conditions de securite', subcategory: null, level: 'Standard', iso_mapping: '8.8', implementation_guidance: 'Inventorier les logiciels en fin de vie. Planifier leur migration. Isoler les systemes ne pouvant etre mis a jour.', verification_guidance: 'Verifier l\'inventaire des logiciels en fin de vie et les plans de migration.', source_url: SOURCE_URL },
  { control_number: '32', title: 'Harden system configurations', title_nl: 'Durcir les configurations systeme', description: 'Apply hardening baselines to operating systems, servers, and network equipment. Disable unnecessary services and default accounts.', description_nl: 'Appliquer des referentiels de durcissement aux systemes d\'exploitation, serveurs et equipements reseau. Desactiver les services et comptes par defaut inutiles.', category: 'Maintenir en conditions de securite', subcategory: null, level: 'Standard', iso_mapping: '8.9', implementation_guidance: 'Appliquer les guides de durcissement ANSSI. Desactiver les services inutiles. Changer les mots de passe par defaut.', verification_guidance: 'Auditer les configurations systeme par rapport aux referentiels de durcissement.', source_url: SOURCE_URL },
  { control_number: '33', title: 'Conduct regular vulnerability scans', title_nl: 'Conduire des scans de vulnerabilites reguliers', description: 'Perform regular vulnerability scans on the information system and remediate identified vulnerabilities.', description_nl: 'Effectuer des scans de vulnerabilites reguliers sur le systeme d\'information et corriger les vulnerabilites identifiees.', category: 'Maintenir en conditions de securite', subcategory: null, level: 'Standard', iso_mapping: '8.8', implementation_guidance: 'Planifier des scans de vulnerabilites trimestriels minimum. Prioriser la remediation selon la criticite.', verification_guidance: 'Verifier la frequence des scans et les delais de remediation.', source_url: SOURCE_URL },

  // Theme 7: Superviser, auditer, reagir (Monitor, audit, react)
  { control_number: '34', title: 'Implement centralized log management', title_nl: 'Mettre en oeuvre une gestion centralisee des journaux', description: 'Collect and centralize security logs from all critical systems in a SIEM or equivalent platform.', description_nl: 'Collecter et centraliser les journaux de securite de tous les systemes critiques dans un SIEM ou une plateforme equivalente.', category: 'Superviser, auditer, reagir', subcategory: null, level: 'Standard', iso_mapping: '8.15', implementation_guidance: 'Deployer un SIEM. Collecter les journaux des pare-feux, serveurs, annuaires, applications critiques. Definir la duree de retention.', verification_guidance: 'Verifier la couverture de collecte et la duree de retention des journaux.', source_url: SOURCE_URL },
  { control_number: '35', title: 'Define and monitor security indicators', title_nl: 'Definir et surveiller des indicateurs de securite', description: 'Define security indicators and monitor them through dashboards to detect anomalies and measure security posture.', description_nl: 'Definir des indicateurs de securite et les surveiller par des tableaux de bord pour detecter les anomalies et mesurer la posture de securite.', category: 'Superviser, auditer, reagir', subcategory: null, level: 'Standard', iso_mapping: '8.16', implementation_guidance: 'Definir des KPI de securite : taux de postes a jour, nombre d\'alertes, delais de remediation. Publier un tableau de bord mensuel.', verification_guidance: 'Examiner le tableau de bord de securite et les tendances.', source_url: SOURCE_URL },
  { control_number: '36', title: 'Establish an incident detection and response capability', title_nl: 'Etablir une capacite de detection et de reponse aux incidents', description: 'Establish a security operations capability (SOC) or equivalent to detect, analyze, and respond to security incidents.', description_nl: 'Etablir une capacite d\'operations de securite (SOC) ou equivalent pour detecter, analyser et repondre aux incidents de securite.', category: 'Superviser, auditer, reagir', subcategory: null, level: 'Renforce', iso_mapping: '5.24', implementation_guidance: 'Creer ou souscrire a un service SOC. Definir les procedures de detection et de reponse. Former les analystes.', verification_guidance: 'Evaluer la capacite de detection par des tests de simulation.', source_url: SOURCE_URL },
  { control_number: '37', title: 'Conduct regular penetration tests', title_nl: 'Conduire des tests d\'intrusion reguliers', description: 'Commission regular penetration tests on exposed services and critical applications to identify exploitable vulnerabilities.', description_nl: 'Commander des tests d\'intrusion reguliers sur les services exposes et les applications critiques pour identifier les vulnerabilites exploitables.', category: 'Superviser, auditer, reagir', subcategory: null, level: 'Renforce', iso_mapping: '8.8', implementation_guidance: 'Planifier des tests d\'intrusion annuels minimum. Tester les services exposes sur Internet et les applications critiques internes.', verification_guidance: 'Verifier la realisation des tests et le suivi des plans d\'action.', source_url: SOURCE_URL },
  { control_number: '38', title: 'Prepare an incident response plan', title_nl: 'Preparer un plan de reponse aux incidents', description: 'Document and test an incident response plan covering detection, containment, eradication, recovery, and post-incident review.', description_nl: 'Documenter et tester un plan de reponse aux incidents couvrant la detection, le confinement, l\'eradication, la reprise et le retour d\'experience.', category: 'Superviser, auditer, reagir', subcategory: null, level: 'Standard', iso_mapping: '5.26', implementation_guidance: 'Rediger un plan de reponse aux incidents. Definir les roles et responsabilites. Tester le plan par des exercices annuels.', verification_guidance: 'Verifier l\'existence du plan et la realisation des exercices.', source_url: SOURCE_URL },

  // Theme 8: Sensibiliser et former (Awareness and training)
  { control_number: '39', title: 'Conduct regular security awareness sessions', title_nl: 'Conduire des sessions de sensibilisation regulieres', description: 'Organize regular security awareness sessions for all staff covering current threats, good practices, and reporting procedures.', description_nl: 'Organiser des sessions de sensibilisation regulieres pour tout le personnel couvrant les menaces actuelles, les bonnes pratiques et les procedures de signalement.', category: 'Sensibiliser et former', subcategory: null, level: 'Standard', iso_mapping: '6.3', implementation_guidance: 'Organiser des sessions de sensibilisation annuelles minimum. Adapter le contenu aux menaces actuelles (phishing, ransomware).', verification_guidance: 'Verifier le taux de participation et la frequence des sessions.', source_url: SOURCE_URL },
  { control_number: '40', title: 'Train IT staff on security', title_nl: 'Former le personnel informatique a la securite', description: 'Provide specialized security training to IT administrators and developers appropriate to their roles.', description_nl: 'Fournir une formation specialisee en securite aux administrateurs informatiques et developpeurs adaptee a leurs roles.', category: 'Sensibiliser et former', subcategory: null, level: 'Standard', iso_mapping: '6.3', implementation_guidance: 'Definir un plan de formation securite par profil (administrateur, developpeur, chef de projet). Inclure des certifications quand pertinent.', verification_guidance: 'Verifier la realisation des formations et les certifications obtenues.', source_url: SOURCE_URL },
  { control_number: '41', title: 'Define an acceptable use charter', title_nl: 'Definir une charte d\'utilisation acceptable', description: 'Establish and communicate an acceptable use charter defining the rules for using the information system.', description_nl: 'Etablir et communiquer une charte d\'utilisation acceptable definissant les regles d\'utilisation du systeme d\'information.', category: 'Sensibiliser et former', subcategory: null, level: 'Standard', iso_mapping: '5.10', implementation_guidance: 'Rediger une charte d\'utilisation du SI. La faire signer par tous les collaborateurs. L\'integrer dans le processus d\'accueil.', verification_guidance: 'Verifier que la charte est signee par tous les collaborateurs.', source_url: SOURCE_URL },
  { control_number: '42', title: 'Conduct phishing simulation exercises', title_nl: 'Conduire des exercices de simulation de phishing', description: 'Run regular phishing simulation campaigns to test and improve staff awareness of social engineering attacks.', description_nl: 'Mener des campagnes regulieres de simulation de phishing pour tester et ameliorer la vigilance du personnel face aux attaques d\'ingenierie sociale.', category: 'Sensibiliser et former', subcategory: null, level: 'Standard', iso_mapping: '6.3', implementation_guidance: 'Mener des campagnes de phishing simule trimestrielles. Analyser les resultats. Former les collaborateurs qui echouent.', verification_guidance: 'Mesurer le taux de clic et son evolution dans le temps.', source_url: SOURCE_URL },
];

mkdirSync(DATA_DIR, { recursive: true });

const output = {
  framework: {
    id: 'anssi-hygiene',
    name: 'IT Security Hygiene Guide (42 Measures)',
    name_nl: 'Guide d\'hygiene informatique (42 mesures)',
    issuing_body: 'Agence nationale de la securite des systemes d\'information (ANSSI)',
    version: '2024',
    effective_date: '2024-01-01',
    scope: 'Foundational IT security hygiene measures for all French organizations, public and private',
    scope_sectors: ['government', 'healthcare', 'finance', 'energy', 'telecom', 'transport', 'education'],
    structure_description: '42 measures organized by theme: know your IS, control access, secure workstations, secure the network, secure administration, maintain security, monitor/audit/react, awareness and training. Each measure has a standard or enhanced level.',
    source_url: 'https://www.ssi.gouv.fr/guide/guide-dhygiene-informatique/',
    license: 'Public sector publication',
    language: 'fr',
  },
  controls,
  metadata: {
    ingested_at: new Date().toISOString(),
    source: 'ANSSI Guide d\'hygiene informatique',
    total_controls: controls.length,
    notes: [
      'The 42 measures are the foundational ANSSI guidance referenced across French public and private sector.',
      'Measures are classified as Standard (baseline) or Renforce (enhanced for sensitive systems).',
      'title_nl holds French text (native language); title holds English translation.',
    ],
  },
};

writeFileSync(OUTPUT_FILE, JSON.stringify(output, null, 2), 'utf-8');
console.log(`ANSSI Hygiene: ${controls.length} controls written to ${OUTPUT_FILE}`);
